name: Start ScanCentral scan

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: fortify/gha-setup-scancentral-client@v1
        with:
          client-auth-token: CHANGEME123!
      - run: scancentral -url http://13.250.132.143:8081/scancentral-ctrl/ start -bt none
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: scancentral-logs
          path: ~/.fortify/scancentral/log
